on:
  push:
    branches: [ "main" ] 
name: SonarCloud analysis    
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Analyze with SonarCloud
       uses: SonarSource/sonarcloud-github-action@master
       with: 
         args: >
            -Dsonar.organization=clopeznoorg
            -Dsonar.projectKey=clopezno_HellosonarQube
            -Dsonar.sources=./src
       env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
